---
- name: Install dependencies
  become: true
  apt:
    name:
      - ca-certificates
      - curl
      - apt-transport-https
      - lsb-release
      - gnupg

- name: Create variable from command
  command: "lsb_release -cs"
  register: lsb_release
  changed_when: lsb_release.rc != 0

- name: "Get distro"
  set_fact:
    distro: "{{ lsb_release.stdout }}"

- name: Add an Apt signing key to a specific keyring file
  become: true
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /etc/apt/trusted.gpg.d/microsoft.gpg

- name: Add specified repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ distro }} main"
    state: present

- name: Install AZ CLI
  become: true
  apt:
    name: azure-cli
