---
- name: Git checkout
  become: true
  ansible.builtin.git:
    repo: "{{ item.name }}"
    dest: "{{ home_dir }}/reference_repos/{{ item.dest }}"
    version: "{{ item.branch }}"
  loop: "{{ repos }}"


- name: This configures the ssh key for github
  become: true
  ansible.builtin.file:
    state: directory
    dest: "{{ home_dir }}/.ssh"
    mode: '0700'
    owner: "{{ user }}"
    group: "{{ group }}"

- name: This configures the ssh key for github
  become: true
  ansible.builtin.copy:
    src: id_rsa
    dest: "{{ home_dir }}/.ssh/id_rsa"
    mode: '0400'
    owner: "{{ user }}"
    group: "{{ group }}"