---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: true

- name: Install gnupg (state=present is optional)
  apt:
    name: gnupg
    state: present

- name: Install software-properties-common (state=present is optional)
  apt:
    name: software-properties-common
    state: present

- name: Install curl (state=present is optional)
  become: true
  apt:
    name: curl
    state: present

- name: Install unzip (state=present is optional)
  become: true
  apt:
    name: unzip
    state: present


- name: Add an Apt signing key, uses whichever key is at the URL
  become: true
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present


- name: Add specified repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com focal main"
    state: present

- name: Install terraform (state=present is optional)
  become: true
  apt:
    name: terraform
    state: present

# tasks file for tfenv
- name: Git checkout tfenv
  ansible.builtin.git:
    repo: "https://github.com/tfutils/tfenv.git"
    dest: "{{ home_dir }}/.tfenv"
    version: master

- name: Create a symbolic link
  become: true
  ansible.builtin.file:
    src: "{{ home_dir }}/.tfenv/bin/tfenv"
    dest: /usr/local/bin/tfenv
    state: link

- name: Install terraform latest (stable)
  ansible.builtin.command: tfenv install 1.0.10
  register: result
  changed_when: false
